uBeSocial/Controllers/UBeSocialTwitterController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Web.Mvc;
using uBeSocial.Services.Interfaces;
using uBeSocial.ViewModels;
using Umbraco.Core.Logging;
using Umbraco.Web.Mvc;

namespace uBeSocial.Controllers
{
    public class UBeSocialTwitterController : UmbracoAuthorizedController
    {
        private readonly ITwitterService _twitterService;
        private readonly ITwitterUserService _twitterUserService;
        private readonly ITwitterConfigurationService _twitterConfigurationService;

        public UBeSocialTwitterController()
        {
            _twitterService = Helpers.DependencyResolver.Instance.Resolve<ITwitterService>();
            _twitterUserService = Helpers.DependencyResolver.Instance.Resolve<ITwitterUserService>();
            _twitterConfigurationService = Helpers.DependencyResolver.Instance.Resolve<ITwitterConfigurationService>();
        }

        public ActionResult Index()
        {
            var users = _twitterUserService.Get().Select(u => new SelectListItem { Text = u.UserName, Value = u.Id.ToString() }).ToList();
            users.Insert(0, new SelectListItem { Text = "Select a user", Value = string.Empty });

            var model = new TwitterDashboardViewModel
            {
                UserId = _twitterConfigurationService.Get()?.TwitterUserId ?? 0,
                Users = users
            };

            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Index(TwitterDashboardViewModel model)
        {
            var configuration = _twitterConfigurationService.Get();
            configuration.TwitterUserId = model.UserId;

            _twitterConfigurationService.Update(configuration);
            TempData["Success"] = "Successfully updated active user";

            return RedirectToAction("Index");
        }

        public ActionResult User(int id)
        {
            var user = _twitterUserService.Get(id);
            if (user == null)
            {
                return HttpNotFound($"No user with id '{id}' was found");
            }

            var model = new TwitterUserViewModel
            {
                Id = id,
                UserName = user.UserName,
                ConsumerKey = user.ConsumerKey,
                ConsumerSecret = user.ConsumerSecret,
                AccessToken = user.AccessToken,
                AccessTokenSecret = user.AccessTokenSecret
            };

            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult User(TwitterUserViewModel model)
        {
            var user = _twitterUserService.Get(model.Id);
            user.ConsumerKey = model.ConsumerKey;
            user.ConsumerSecret = model.ConsumerSecret;
            user.AccessToken = model.AccessToken;
            user.AccessTokenSecret = model.AccessTokenSecret;

            _twitterUserService.Update(user);

            TempData["Success"] = "Successfully updated user.";

            return RedirectToAction("User", new { id = user.Id });
        }

        [HttpPost]
        public ActionResult Tweet(string tweet)
        {
            try
            {
                _twitterService.Post(tweet);
            }
            catch (Exception ex)
            {
                LogHelper.Error<UBeSocialTwitterController>("An unexpected error occurred posting to Twitter", ex);
                return Json(new { Success = false, Message = ex.Message });
            }

            return Json(new { Success = true, Message = "Successfully posted status to Twitter" });
        }
    }
}

uBeSocial/Views/UBeSocialTwitter/Index.cshtml
@inherits WebViewPage<uBeSocial.ViewModels.TwitterDashboardViewModel>
@{
    Layout = null;
    var successMessage = TempData["Success"] as string;
}
<!DOCTYPE html>
<html>
<head>
    <title>uBeSocial Twitter Configuration</title>

    <!-- Umbraco Styles -->
    <link type="text/css" rel="stylesheet" href="/umbraco_client/Ui/default.css" />
    <link type="text/css" rel="stylesheet" href="/umbraco_client/modal/style.css" />
    <link type="text/css" rel="stylesheet" href="/umbraco_client/Scrollingmenu/style.css" />
    <link type="text/css" rel="stylesheet" href="/umbraco_client/Propertypane/style.css" />
    <link type="text/css" rel="stylesheet" href="/umbraco_client/Panel/style.css" />
    <link type="text/css" rel="stylesheet" href="/umbraco_client/Tabview/style.css" />

    <!-- Bootstrap Files-->
    <link type="text/css" rel="stylesheet" href="@Url.Content("~/UBeSocialStaticResources/bootstrap/styles/bootstrap.min.css")" />
    <script src="@Url.Content("~/UBeSocialStaticResources/scripts/jquery/jquery-1.9.1.min.js")"></script>
    <script src="@Url.Content("~/UBeSocialStaticResources/bootstrap/scripts/bootstrap.min.js")"></script>
</head>
<body class="umbracoPage">
    <div class="header">
        <ul>
            <li class="tabOn"><a><span>uBeSocial Twitter Configuration</span></a></li>
        </ul>
    </div>
    <div class="tabpagecontainer">
        <div class="tabpage" style="display: block;">
            <div class="menubar"></div>
            <div class="tabpagescrollinglayer">
                <div class="tabpageContent">
                    <div class="propertyPane" style="padding: 0 10px 10px 10px;">
                        <header></header>
                        <div>
                            <h1>uBeSocial Twitter</h1>
                            @if (!string.IsNullOrWhiteSpace(successMessage))
                            {
                                <div class="alert alert-success">
                                    @successMessage
                                </div>
                            }
                            <p>Select the user you would like to use to tweet content using uBeSocial. If you have not created any users yet, you can create them in the left sidebar by right clicking on the Twitter node and clicking create.</p>
                            @using (Html.BeginForm("Index", "UBeSocialTwitter", FormMethod.Post, new {@class = "form-horizontal"}))
                            {
                                @Html.AntiForgeryToken()
                                <div class="form-group">
                                    <label class="control-label col-sm-2">User:</label>
                                    <div class="col-sm-8">
                                        @Html.DropDownListFor(m => m.UserId, Model.Users, new { @class = "form-control" })
                                    </div>
                                    <div class="col-sm-2">
                                        <button type="submit" class="btn btn-primary">Save</button>
                                    </div>
                                </div>
                            }
                        </div>
                        <footer>
                            <code>uBeSocial Version @Model.Version</code>
                        </footer>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="footer">
        <div class="status">
        </div>
    </div>
</body>
</html>

uBeSocial/Views/UBeSocialTwitter/User.cshtml
@inherits WebViewPage<uBeSocial.ViewModels.TwitterUserViewModel>
@{
    Layout = null;
    var successMessage = TempData["Success"] as string;
}
<!DOCTYPE html>
<html>
<head>
    <title>uBeSocial Twitter Configuration</title>

    <!-- Umbraco Styles -->
    <link type="text/css" rel="stylesheet" href="/umbraco_client/Ui/default.css" />
    <link type="text/css" rel="stylesheet" href="/umbraco_client/modal/style.css" />
    <link type="text/css" rel="stylesheet" href="/umbraco_client/Scrollingmenu/style.css" />
    <link type="text/css" rel="stylesheet" href="/umbraco_client/Propertypane/style.css" />
    <link type="text/css" rel="stylesheet" href="/umbraco_client/Panel/style.css" />
    <link type="text/css" rel="stylesheet" href="/umbraco_client/Tabview/style.css" />

    <!-- Bootstrap Files-->
    <link type="text/css" rel="stylesheet" href="@Url.Content("~/UBeSocialStaticResources/bootstrap/styles/bootstrap.min.css")" />
    <script src="@Url.Content("~/UBeSocialStaticResources/scripts/jquery/jquery-1.9.1.min.js")"></script>
    <script src="@Url.Content("~/UBeSocialStaticResources/bootstrap/scripts/bootstrap.min.js")"></script>
</head>
<body class="umbracoPage">
    <div class="header">
        <ul>
            <li class="tabOn"><a><span>Edit @Model.UserName</span></a></li>
        </ul>
    </div>
    <div class="tabpagecontainer">
        <div class="tabpage" style="display: block;">
            <div class="menubar"></div>
            <div class="tabpagescrollinglayer">
                <div class="tabpageContent">
                    <div class="propertyPane" style="padding: 0 10px 10px 10px;">
                        <header></header>
                        <div>
                            <h1>User: @Model.UserName</h1>
                            @if (!string.IsNullOrWhiteSpace(successMessage))
                            {
                                <div class="alert alert-success">
                                    @successMessage
                                </div>
                            }
                            @using (Html.BeginForm("User", "UBeSocialTwitter", FormMethod.Post, new {@class = "form-horizontal"}))
                            {
                                @Html.AntiForgeryToken()
                                @Html.HiddenFor(m => m.Id)
                                <div class="form-group">
                                    <label class="control-label col-sm-2">Consumer Key:</label>
                                    <div class="col-sm-8">
                                        @Html.TextBoxFor(m => m.ConsumerKey, new {@class = "form-control"})
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label class="control-label col-sm-2">Consumer Secret:</label>
                                    <div class="col-sm-8">
                                        @Html.TextBoxFor(m => m.ConsumerSecret, new {@class = "form-control"})
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label class="control-label col-sm-2">Access Token:</label>
                                    <div class="col-sm-8">
                                        @Html.TextBoxFor(m => m.AccessToken, new {@class = "form-control"})
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label class="control-label col-sm-2">Access Token Secret:</label>
                                    <div class="col-sm-8">
                                        @Html.TextBoxFor(m => m.AccessTokenSecret, new {@class = "form-control"})
                                    </div>
                                </div>
                                <div class="col-sm-offset-2">
                                    <button type="submit" class="btn btn-primary">Submit</button>
                                </div>
                            }
                        </div>
                        <footer>
                            <code>uBeSocial Version @Model.Version</code>
                        </footer>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="footer">
        <div class="status">
        </div>
    </div>
</body>
</html>